name: ai_safety_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^3.1.2
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  meta: ^1.15.0
  shared_preferences: ^2.3.5
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/intro/
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Medium.ttf
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
